module.exports = {
    BEGIN_AUTHENTICATION: 'BEGIN_AUTHENTICATION',
    END_AUTHENTICATION_SUCCESS: 'END_AUTHENTICATION_SUCCESS',
    END_AUTHENTICATED_FAILURE: 'END_AUTHENTICATED_FAILURE',

    BEGIN_CHECK: 'BEGIN_CHECK',
    END_CHECK_SUCCESS: 'END_CHECK_SUCCESS',
    END_CHECK_FAILURE: 'END_CHECK_FAILURE'
};