module.exports = {
    BEGIN_GENERATE_MAP: 'BEGIN_GENERATE_MAP',
    END_GENERATE_MAP_SUCCESS: 'END_GENERATE_MAP_SUCCESS',
    END_GENERATE_MAP_FAILURE: 'END_GENERATE_MAP_FAILURE',

    REVEAL_ITEM: 'REVEAL_ITEM',
    REVEAL_ALL_ITEMS: 'REVEAL_ALL_ITEMS'
};