module.exports = {
    PLAYER_MOUSE_MOVE: 'PLAYER_MOUSE_MOVE',
    PLAYER_MOUSE_ENTER: 'PLAYER_MOUSE_ENTER',
    PLAYER_MOUSE_LEAVE: 'PLAYER_MOUSE_LEAVE',

    PLAYER_MOUSE_DOWN: 'PLAYER_MOUSE_DOWN',
    PLAYER_MOUSE_UP: 'PLAYER_MOUSE_UP',

    PLAYER_KEY_PRESS: 'PLAYER_KEY_PRESS',
    PLAYER_KEY_UP: 'PLAYER_KEY_UP',
    PLAYER_KEY_DOWN: 'PLAYER_KEY_DOWN',

    GAME_OVER: 'GAME_OVER'
};